const DASHBOARD_ACTIONS = {
  DASHBOARD: {
    PENDING: 'DASHBOARD_PENDING',
    SUCCESS: 'DASHBOARD_SUCCESS',
    FAILURE: 'DASHBOARD_FAILURE',
    UPDATE: 'DASHBOARD_UPDATE',
  }
}

export const DASHBOARD_STATE = {
  REFRESHED: 'DASHBOARD_REFRESHED',
  IN_PROGRESS: 'DASHBOARD_PROGRESS',
  SUCCESS: 'DASHBOARD_RETRIEVED',
  ERROR: 'DASHBOARD_ERROR',
}

export default DASHBOARD_ACTIONS
